URLCatDic={
    "extr":"Extreme",
    "fash":"Fashion",
    "lol":"Humor",
    "fnnc":"Finance",
    "date":"Dating",
    "infr":"Infrastructure and Content Delivery Networks",
    "tran":"Web Page Translation",
    "adlt":"Adult",
    "pnet":"Professional Networking",
    "mail":"Web-Based Email",
    "game":"Games",
    "gamb":"Gambling",
    "fts":"File Transfer Services",
    "drug":"Illegal Drugs",
    "ildl":"Illegal Downloads",
    "filt":"Filter Avoidance",
    "socs":"Social Science",
    "comm":"Online Communities",
    "job":"Job Search",
    "sxed":"Sex Education",
    "nsn":"Non-Sexual Nudity",
    "trvl":"Travel",
    "aud":"Streaming Audio",
    "hate":"Hate Speech",
    "cprn":"Child Abuse Content",
    "lotr":"Lotteries",
    "dyn":"Dynamic and Residential",
    "art":"Arts",
    "sprt":"Sports and Recreation",
    "kids":"Safe for Kids",
    "comp":"Computers and Internet",
    "park":"Parked Domains",
    "gov":"Government and Law",
    "rest":"Real Estate",
    "plag":"Cheating and Plagiarism",
    "alc":"Alcohol",
    "osb":"Online Storage and Backup",
    "tob":"Tobacco",
    "whst":"Web Hosting",
    "astr":"Astrology",
    "trad":"Online Trading",
    "cell":"Mobile Phones",
    "food":"Dining and Drinking",
    "vid":"Streaming Video",
    "natr":"Nature",
    "saas":"and B2B",
    "adv":"Advertisements",
    "swup":"Software Updates",
    "pers":"Personal Sites",
    "p2p":"Peer File Transfer",
    "ref":"Reference",
    "snet":"Social Networking",
    "scty":"Society and Culture",
    "chat":"Chat and Instant Messaging",
    "csec":"Computer Security",
    "pol":"Politics",
    "ngo":"Non-Governmental Organizations",
    "edu":"Education",
    "hack":"Hacking",
    "shop":"Shopping",
    "voip":"Internet Telephony",
    "auct":"Auctions",
    "ling":"Lingerie and Swimsuits",
    "news":"News",
    "img":"Photo Searches and Images",
    "ent":"Entertainment",
    "trns":"Transportation",
    "porn":"Pornography",
    "srch":"Search Engines and Portals",
    "pem":"Organizational Email",
    "free":"Freeware and Shareware",
    "ilac":"Illegal Activities",
    "rel":"Religion",
    "busi":"Business and Industry",
    "sci":"Science and Technology",
    "card":"Digital Postcards",
    "hlth":"Health and Nutrition",
    "weap":"Weapons",
}

MalwareDictionary={
    "-": "Not Set",
    "0": "Unknown",
    "1": "Not Scanned",
    "2": "Timeout",
    "3": "Error",
    "4": "Unscannable",
    "10": "Generic Spyware",
    "12": "Browser Helper Object",
    "13": "Adware",
    "14": "System Monitor",
    "18": "Commercial System Monitor",
    "19": "Dialer",
    "20": "Hijacker",
    "21": "Phishing URL",
    "22": "Trojan Downloader",
    "23": "Trojan Horse",
    "24": "Trojan Phisher",
    "25": "Worm",
    "26": "Encrypted File",
    "27": "Virus",
    "33": "Other Malware",
    "34": "PUA",
    "35": "Aborted",
    "36": "Outbreak Heuristics",
    "37": "Known Malicious and High-Risk Files"
}